# Tech Stack : Express + MongoDB
# Hosted : Heroku Free Tier (USA N.Virginia)
# GitHub Repo : https://github.com/xritzx/smallcase_hiring.git

## NOTE: Please install `humao.rest-client` in VS Code to use the APIs ##

@base_url = https://smallcase-hiring-ritankar.herokuapp.com

// Fetch All trades grouped by securities
GET {{base_url}}/trade HTTP/1.1
###

// Get Portfolio security grouped aggregate of trades
GET {{base_url}}/trade/portfolio HTTP/1.1
###

// Get net returns
GET {{base_url}}/trade/returns HTTP/1.1
###


// Add Trade
POST {{base_url}}/trade HTTP/1.1
content-type: application/json

{
    "ticker": "WIPRO",
    "price": 50,
    "type": "buy",
    "shares_added": 10
}
###


// Update Trade
POST {{base_url}}/trade/update HTTP/1.1
content-type: application/json

{
    "_id": "60ae6ac55e062c36c85e2a1c",
    "ticker": "CTS",
    "price": 10,
    "type": "sell",
    "shares_added": 5
}
###


POST {{base_url}}/trade/delete HTTP/1.1
content-type: application/json

{
    "_id": "60aeac378ec48d3f1e1455fd"
}
###
